sqlite:
  :adapter: sqlite
  :database: vendor/plugins/racer/spec/support/racer_plugin.sqlite.db

sqlite3:
  :adapter: sqlite3
  :database: vendor/plugins/racer/spec/support/racer_plugin.sqlite3.db

postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: racer_plugin_test
  :min_messages: ERROR

mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password: password
  :database: racer_plugin_test
